### ISSUE TITLE
any 

### ISSUE THREAD

**Issue by ericzwong** [nosco/hx#54]
This error occurs when I develop an npm package based on a hook and then reference it in another project:
https://reactjs.org/warnings/invalid-hook-call-warning.html

i find the problem is "You might have more than one copy of React in the same app."

**Comment by lilactown** [comment]
This sounds like you are either bundling React with your npm module (you shouldn’t) or you are using the hook incorrectly.

Specifically re: bundling, this is not something hx can help you with. If you’re using shadow-cljs, I would ask in the #shadow-cljs channel in slack or [open an issue](https://github.com/thheller/shadow-cljs).
