### ISSUE TITLE
Push missing tags + maybe a 0.5.4 release

### ISSUE THREAD

**Issue by martinklepsch** [nosco/hx#62]
Besides the tags it also seems that the `0.5.3` release that's on Clojars might be a mishap. It's not documented in the changelog and it contains a `hx/hiccup/tag.cljc` file that requires `goog.obj` instead of `goog.object` resulting in analyzer errors.

**Comment by lilactown** [comment]
Hm, slipped into the JAR totally on accident - it was a file left over from an experimental branch.

**Comment by lilactown** [comment]
I've created a tag for 0.5.3. I'm not sure I want to publish a new release just to remove an undocumented source file in the jar. Is this necessary for your tests with external JS on cljdoc @martinklepsch ?
