### ISSUE TITLE
hx.hooks/useMemo  deps as CLJS collection?

### ISSUE THREAD

**Issue by aiba** [nosco/hx#67]
[docs for hx.hooks/useMemo](https://github.com/Lokeh/hx/blob/master/docs/state-management.md#usememo-f-deps) say that deps can be a cljs collection, but I don't think this is true according to [the source](https://github.com/Lokeh/hx/blob/master/src/hx/hooks.cljs#L148).

Shall we update useMemo?  While we're at it, we can make deps optional for convenience.

```
(defn useMemo [f & [deps]]
  (react/useMemo f (to-array (or deps []))))
```

Would you accept this PR?

**Comment by lilactown** [comment]
I would accept a PR for this.
