### ISSUE TITLE
Typo in package 0.5.3 (maybe broken)

### ISSUE THREAD

**Issue by frozar** [nosco/hx#69]
I tried to analyse the lilactown/hx v0.5.3 package with cljdoc-analyzer project.

I discover that in the file `hx/hiccup/tag.cljc`, there is a use of the package `goog.obj` as dependency. But this package doesn't exist, the correct name is `goog.object`.

By the way, the file `hx/hiccup/tag.cljc` doesn't exist anymore on the master branch, so maybe you should generate a new version of the hx package, v0.5.4
Just to get the latest package analysable by cljdoc (if cljdoc cannot anaylise it, it's possible that no one can use it...).

**Comment by lilactown** [comment]
Thanks for reporting! It looks like this is a case of a local file on my hard drive getting placed into the JAR when deploying to clojars.

I don't think there's an expectation that cljdoc has documentation for hx and so I won't prioritize an update; as long as this isn't breaking anything too bad. If you want to remove hx from cljdocs, that would be fine. FWIW, I would love to have cljdoc support for lilactow/helix which is the successor to this lib and much more maintained.

That namespace was an experiment that I later deleted, and is not referenced by any other file in the project. Users can require at their own peril. 😄 

If/when I do another release, I'll ensure that file isn't there though so as to correct this minor mistake.

**Comment by frozar** [comment]
Haha, funny, I mean it seems like an "no issue" detected.

Cljdoc don't have documentation for hx, but for a reason I'm not aware of, there is a test of cljdoc-analyzer against hx project, and so today I just see that it failed on v0.5.3 but work on v0.5.2

Cljdoc takes a package as entry, and extracts documentation from the docstrings. I'm not a specialist of cljdoc, I discovered it recently by using the CircleCI service to test my package (roughcljs). CircleCI seems to automatically run cljdoc on your code. If you're interested to have nice online documentation almost for free, you should check the CircleCI service :)

As it's a "no issue", I close it.

**Comment by lilactown** [comment]
@frozar ah I see! I think I talked to martin about hx + cljdoc awhile ago but ran into issues with npm deps. Probably smart to remove hx from the tests, since it's not well supported now.
